#!/bin/bash
echo $(( $(echo ${WATER} | tr -d '.' | tr 'water' '01234') + $(echo ${STIR//./} | tr 'stir' '0123') )) | awk '{digits="bestchol"; while($1){r=$1%8; $1=int($1/8); s=substr(digits,r+1,1) s;} print s}'
