#!/usr/bin/env bash
# Script to transfer a file to a remote server

# Check if the correct number of arguments is provided
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Store arguments into variables
FILE_PATH=$1         # Path to the file to transfer
SERVER_IP=$2         # IP address of the server
USERNAME=$3          # SSH username
SSH_KEY=$4           # Path to SSH private key

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

exit 0
