#!/bin/bash

# Check if less than 4 parameters passed
if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE_PATH=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# Use scp to transfer file to user's home directory, disable strict host key checking
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$IP:~/"
