#!/usr/bin/env bash
# Configures a new Ubuntu server with a custom HTTP header and a /redirect_me 301 redirect

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo 'Holberton School' > /var/www/html/index.nginx-debian.html

# Add the custom header inside the server block
sed -i '/listen 80 default_server;/a \
    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Add location block for /redirect_me redirect before the last }
sed -i '/^}$/i \
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

service nginx restart
